// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = JobsSlice | HighlightSlice | ExpertisesSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
	 * Meta Title field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>;

type WorkDocumentDataSlicesSlice = never;

/**
 * Content for work documents
 */
interface WorkDocumentData {
	/**
	 * Slice Zone field in *work*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<WorkDocumentDataSlicesSlice> /**
	 * Meta Title field in *work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: work.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: work.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *work*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, 'work', Lang>;

export type AllDocumentTypes = HomeDocument | WorkDocument;

/**
 * Item in *Expertises → Default → Primary → expertise*
 */
export interface ExpertisesSliceDefaultPrimaryExpertiseItem {
	/**
	 * thumbnail field in *Expertises → Default → Primary → expertise*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[].thumbnail
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumbnail: prismic.ImageField<never>;

	/**
	 * name field in *Expertises → Default → Primary → expertise*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * link field in *Expertises → Default → Primary → expertise*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Expertises → Default → Primary*
 */
export interface ExpertisesSliceDefaultPrimary {
	/**
	 * title field in *Expertises → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * expertise field in *Expertises → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	expertise: prismic.GroupField<
		Simplify<ExpertisesSliceDefaultPrimaryExpertiseItem>
	>;
}

/**
 * Default variation for Expertises Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExpertisesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ExpertisesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Expertises*
 */
type ExpertisesSliceVariation = ExpertisesSliceDefault;

/**
 * Expertises Shared Slice
 *
 * - **API ID**: `expertises`
 * - **Description**: Expertises
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExpertisesSlice = prismic.SharedSlice<
	'expertises',
	ExpertisesSliceVariation
>;

/**
 * Primary content in *Highlight → Default → Primary*
 */
export interface HighlightSliceDefaultPrimary {
	/**
	 * title field in *Highlight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * description field in *Highlight → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: use {{data}} to add data
	 * - **API ID Path**: highlight.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * variable field in *Highlight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.default.primary.variable
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	variable: prismic.KeyTextField;
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HighlightSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation = HighlightSliceDefault;

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<
	'highlight',
	HighlightSliceVariation
>;

/**
 * Item in *Jobs → Default → Primary → jobs*
 */
export interface JobsSliceDefaultPrimaryJobsItem {
	/**
	 * thumbnail field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].thumbnail
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumbnail: prismic.ImageField<never>;

	/**
	 * job field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].job
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	job: prismic.KeyTextField;

	/**
	 * company field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].company
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	company: prismic.KeyTextField;

	/**
	 * job_start_date field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].job_start_date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	job_start_date: prismic.DateField;

	/**
	 * job_end_date field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].job_end_date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	job_end_date: prismic.DateField;
}

/**
 * Primary content in *Jobs → Default → Primary*
 */
export interface JobsSliceDefaultPrimary {
	/**
	 * title field in *Jobs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * jobs field in *Jobs → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	jobs: prismic.GroupField<Simplify<JobsSliceDefaultPrimaryJobsItem>>;
}

/**
 * Default variation for Jobs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<JobsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Jobs*
 */
type JobsSliceVariation = JobsSliceDefault;

/**
 * Jobs Shared Slice
 *
 * - **API ID**: `jobs`
 * - **Description**: Jobs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobsSlice = prismic.SharedSlice<'jobs', JobsSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			WorkDocument,
			WorkDocumentData,
			WorkDocumentDataSlicesSlice,
			AllDocumentTypes,
			ExpertisesSlice,
			ExpertisesSliceDefaultPrimaryExpertiseItem,
			ExpertisesSliceDefaultPrimary,
			ExpertisesSliceVariation,
			ExpertisesSliceDefault,
			HighlightSlice,
			HighlightSliceDefaultPrimary,
			HighlightSliceVariation,
			HighlightSliceDefault,
			JobsSlice,
			JobsSliceDefaultPrimaryJobsItem,
			JobsSliceDefaultPrimary,
			JobsSliceVariation,
			JobsSliceDefault,
		};
	}
}
