// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → networks*
 */
export interface FooterDocumentDataNetworksItem {
	/**
	 * thumbnail field in *Footer → networks*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.networks[].thumbnail
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumbnail: prismic.ImageField<never>;

	/**
	 * link field in *Footer → networks*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.networks[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * title field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * mail field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.mail
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	mail: prismic.KeyTextField;

	/**
	 * networks field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.networks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	networks: prismic.GroupField<Simplify<FooterDocumentDataNetworksItem>>;

	/**
	 * copyright field in *Footer*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.copyright
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	copyright: prismic.RichTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<FooterDocumentData>,
		'footer',
		Lang
	>;

/**
 * Item in *Header → navigation*
 */
export interface HeaderDocumentDataNavigationItem {
	/**
	 * label field in *Header → navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.navigation[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * link field in *Header → navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * logo field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * navigation field in *Header*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<HeaderDocumentData>,
		'header',
		Lang
	>;

type HomeDocumentDataSlicesSlice =
	| WorksSlice
	| JobsSlice
	| HighlightSlice
	| ExpertisesSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
	 * Meta Title field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>;

type WorkDocumentDataSlicesSlice = ImageSlice | AboutSlice | TextImageSlice;

/**
 * Content for work documents
 */
interface WorkDocumentData {
	/**
	 * Slice Zone field in *work*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<WorkDocumentDataSlicesSlice> /**
	 * Meta Title field in *work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: work.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Subtitle field in *work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.meta_subtitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_subtitle: prismic.KeyTextField;

	/**
	 * Meta Description field in *work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: work.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *work*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, 'work', Lang>;

export type AllDocumentTypes =
	| FooterDocument
	| HeaderDocument
	| HomeDocument
	| WorkDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
	/**
	 * title field in *About → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * paragraph field in *About → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AboutSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<'about', AboutSliceVariation>;

/**
 * Item in *Expertises → Default → Primary → expertise*
 */
export interface ExpertisesSliceDefaultPrimaryExpertiseItem {
	/**
	 * thumbnail field in *Expertises → Default → Primary → expertise*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[].thumbnail
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumbnail: prismic.ImageField<never>;

	/**
	 * name field in *Expertises → Default → Primary → expertise*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * link field in *Expertises → Default → Primary → expertise*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Expertises → Default → Primary*
 */
export interface ExpertisesSliceDefaultPrimary {
	/**
	 * title field in *Expertises → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * expertise field in *Expertises → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: expertises.default.primary.expertise[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	expertise: prismic.GroupField<
		Simplify<ExpertisesSliceDefaultPrimaryExpertiseItem>
	>;
}

/**
 * Default variation for Expertises Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExpertisesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ExpertisesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Expertises*
 */
type ExpertisesSliceVariation = ExpertisesSliceDefault;

/**
 * Expertises Shared Slice
 *
 * - **API ID**: `expertises`
 * - **Description**: Expertises
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExpertisesSlice = prismic.SharedSlice<
	'expertises',
	ExpertisesSliceVariation
>;

/**
 * Primary content in *Highlight → Default → Primary*
 */
export interface HighlightSliceDefaultPrimary {
	/**
	 * title field in *Highlight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * description field in *Highlight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * variable field in *Highlight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.default.primary.variable
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	variable: prismic.KeyTextField;
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HighlightSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Highlight → Hero → Primary*
 */
export interface HighlightSliceHeroPrimary {
	/**
	 * title field in *Highlight → Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.hero.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * description field in *Highlight → Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.hero.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;

	/**
	 * variable field in *Highlight → Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlight.hero.primary.variable
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	variable: prismic.KeyTextField;
}

/**
 * Hero variation for Highlight Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceHero = prismic.SharedSliceVariation<
	'hero',
	Simplify<HighlightSliceHeroPrimary>,
	never
>;

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation = HighlightSliceDefault | HighlightSliceHero;

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<
	'highlight',
	HighlightSliceVariation
>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * picture field in *Image → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.default.primary.picture
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	picture: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Item in *Jobs → Default → Primary → jobs*
 */
export interface JobsSliceDefaultPrimaryJobsItem {
	/**
	 * thumbnail field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].thumbnail
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	thumbnail: prismic.ImageField<never>;

	/**
	 * job field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].job
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	job: prismic.KeyTextField;

	/**
	 * company field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].company
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	company: prismic.KeyTextField;

	/**
	 * job_start_date field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].job_start_date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	job_start_date: prismic.DateField;

	/**
	 * job_end_date field in *Jobs → Default → Primary → jobs*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[].job_end_date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	job_end_date: prismic.DateField;
}

/**
 * Primary content in *Jobs → Default → Primary*
 */
export interface JobsSliceDefaultPrimary {
	/**
	 * title field in *Jobs → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * jobs field in *Jobs → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: jobs.default.primary.jobs[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	jobs: prismic.GroupField<Simplify<JobsSliceDefaultPrimaryJobsItem>>;
}

/**
 * Default variation for Jobs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<JobsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Jobs*
 */
type JobsSliceVariation = JobsSliceDefault;

/**
 * Jobs Shared Slice
 *
 * - **API ID**: `jobs`
 * - **Description**: Jobs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JobsSlice = prismic.SharedSlice<'jobs', JobsSliceVariation>;

/**
 * Primary content in *TextImage → Default → Primary*
 */
export interface TextImageSliceDefaultPrimary {
	/**
	 * paragraph field in *TextImage → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_image.default.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	paragraph: prismic.KeyTextField;

	/**
	 * picture field in *TextImage → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_image.default.primary.picture
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	picture: prismic.ImageField<never>;
}

/**
 * Default variation for TextImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TextImage*
 */
type TextImageSliceVariation = TextImageSliceDefault;

/**
 * TextImage Shared Slice
 *
 * - **API ID**: `text_image`
 * - **Description**: TextImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageSlice = prismic.SharedSlice<
	'text_image',
	TextImageSliceVariation
>;

/**
 * Item in *Works → Default → Primary → link*
 */
export interface WorksSliceDefaultPrimaryLinkItem {
	/**
	 * label field in *Works → Default → Primary → link*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: works.default.primary.link[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * href field in *Works → Default → Primary → link*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: works.default.primary.link[].href
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	href: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Works → Default → Primary*
 */
export interface WorksSliceDefaultPrimary {
	/**
	 * title field in *Works → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: works.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * works field in *Works → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: works.default.primary.works
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	works: prismic.NumberField;

	/**
	 * link field in *Works → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: works.default.primary.link[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	link: prismic.GroupField<Simplify<WorksSliceDefaultPrimaryLinkItem>>;
}

/**
 * Default variation for Works Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<WorksSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Works*
 */
type WorksSliceVariation = WorksSliceDefault;

/**
 * Works Shared Slice
 *
 * - **API ID**: `works`
 * - **Description**: Works
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksSlice = prismic.SharedSlice<'works', WorksSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataNetworksItem,
			HeaderDocument,
			HeaderDocumentData,
			HeaderDocumentDataNavigationItem,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			WorkDocument,
			WorkDocumentData,
			WorkDocumentDataSlicesSlice,
			AllDocumentTypes,
			AboutSlice,
			AboutSliceDefaultPrimary,
			AboutSliceVariation,
			AboutSliceDefault,
			ExpertisesSlice,
			ExpertisesSliceDefaultPrimaryExpertiseItem,
			ExpertisesSliceDefaultPrimary,
			ExpertisesSliceVariation,
			ExpertisesSliceDefault,
			HighlightSlice,
			HighlightSliceDefaultPrimary,
			HighlightSliceHeroPrimary,
			HighlightSliceVariation,
			HighlightSliceDefault,
			HighlightSliceHero,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			JobsSlice,
			JobsSliceDefaultPrimaryJobsItem,
			JobsSliceDefaultPrimary,
			JobsSliceVariation,
			JobsSliceDefault,
			TextImageSlice,
			TextImageSliceDefaultPrimary,
			TextImageSliceVariation,
			TextImageSliceDefault,
			WorksSlice,
			WorksSliceDefaultPrimaryLinkItem,
			WorksSliceDefaultPrimary,
			WorksSliceVariation,
			WorksSliceDefault,
		};
	}
}
