// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue';
import { defineSliceZoneComponents } from '@prismicio/vue';

export const components = defineSliceZoneComponents({
	expertises: defineAsyncComponent(() => import('./Expertises/index.vue')),
	highlight: defineAsyncComponent(() => import('./Highlight/index.vue')),
	jobs: defineAsyncComponent(() => import('./Jobs/index.vue')),
});
